# Generated by Django 5.1.3 on 2024-11-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-placed_at"]},
        ),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.EmailField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="first_name",
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name="order",
            name="last_name",
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="phone_number",
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="state",
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
