# Generated by Django 5.1.3 on 2024-11-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_options_order_address_order_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="first_name",
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name="order",
            name="last_name",
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=models.CharField(default=None, max_length=20),
        ),
    ]
