# Generated by Django 5.1.3 on 2024-11-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Description", models.TextField(blank=True, null=True)),
                ("Price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("imageUrl", models.URLField()),
                ("Updated_at", models.DateField(auto_now=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
