# Generated by Django 5.1.3 on 2024-11-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="Name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="Price",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="Updated_at",
            new_name="updated_at",
        ),
    ]
