# Generated by Django 5.1.3 on 2024-11-16 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"]},
        ),
    ]
